### PR TITLE
[desktop_drop] temporary workaround to ignore the redundant signal on KDE

### LINKED ISSUE #324: [Linux] [KDE Plasma] `onDragEntered` and `onDragUpdated` triggered when user come back from another window
## Reproduce Steps
1. Click another window
2. Move the cursor back to flutter app
3. Click the `DropTarget`
4. `onDragEntered` or `onDragUpdated` is triggered. 

## Expected behavior

A single click should not trigger anything.

**Version (please complete the following information):**
 - Flutter Version: 3.19.4
 - OS: Linux
 - plugin: desktop_drop: 0.4.4

https://github.com/MixinNetwork/flutter-plugins/assets/14086980/f6deb938-40c2-45cf-b27c-3fc18c727303

### PR DESCRIPTION
**Pull request by sun-jiao**
closes #324 

This pr should be reverted once  [GTK issue #5519](https://gitlab.gnome.org/GNOME/gtk/-/issues/5519) and [KDE issue #464196](https://bugs.kde.org/show_bug.cgi?id=464196) resolved.

### CODE REVIEW

**Comment by sun-jiao** [comment]
I also created another workaround using native code: https://github.com/sun-jiao/flutter-plugins/tree/native-kde-workaround which one do you prefer?

**Comment by boyan01** [comment]
Sorry for later, Thanks for the detailed description and bug FIX 💙 

I prefer the fix which only affect linux platform native code.  https://github.com/sun-jiao/flutter-plugins/tree/native-kde-workaround.  The impact of this change is minimal and will not affect dart's logic.

**Comment by sun-jiao** [comment]
@boyan01 ok, I have updated it.

**Comment by boyan01** [comment]
LGTM

**Pull request merged**
